# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('canciones', models.CharField(max_length=512)),
                ('fecha_lanzamiento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256, unique=True)),
                ('integrantes', models.CharField(max_length=512)),
                ('fecha_inicio', models.DateTimeField()),
                ('genero', models.ManyToManyField(to='djandoApp.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='publicacion',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djandoApp.Usuario'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djandoApp.Grupo_artista'),
        ),
        migrations.AddField(
            model_name='album',
            name='grupo_artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djandoApp.Grupo_artista'),
        ),
    ]
