# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djandoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
